version: "3"
services:
  ui:
    build: ./ui
    ports: ['6001:5173']
    volumes:
      - .:/workspace
  backend:
    build: ./backend
    environment:
      FLASK_DEBUG: 1
    ports: ['6002:8080']
    volumes:
      - .:/workspace