version: "3"
services:
  ui:
    build: ./ui
    ports: ['5002:5173']
    volumes:
      - ./ui:/workspace/ui
    tty: true
  api:
    build: ./app
    environment:
      FLASK_DEBUG: 1
    ports: ['3001:8080']
    volumes:
      - .:/workspace