version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mktbot-serverless"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1je8zk9oofmg0"
s3_prefix = "mktbot-serverless"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = ["FlaskFunction=553143883356.dkr.ecr.us-east-1.amazonaws.com/mktbotserverlessc65d5e77/flaskfunctionf9708d47repo"]
